[build]
  command   = "npm run build"
  publish   = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION             = "18"
  NPM_VERSION              = "10"
  GENERATE_SOURCEMAP       = "false"
  CI                       = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"

# Serve the SPA for all routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
